version: "3"

services:
  server:
    build: ./
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_db:
    driver: local