spring:
  config:
    activate:
      on-profile: local
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5432/postgres
      name: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      username: postgres
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092