spring:
  config:
    activate:
      on-profile: docker
  datasource:
    postgres:
      url: jdbc:postgresql://postgres:5432/postgres
      name: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      username: postgres
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: redis
      port: 6379