spring:
  config:
    activate:
      on-profile: docker
  datasource:
    postgres:
      url: jdbc:postgresql://postgres:5432/postgres
      name: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      username: postgres
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
