version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_db:
    driver: local